# Generated by Django 4.2.4 on 2023-08-29 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('titel', models.CharField(max_length=30)),
                ('discription', models.CharField(max_length=50)),
                ('statas', models.CharField(max_length=40)),
            ],
        ),
        migrations.DeleteModel(
            name='listModel',
        ),
    ]
